name: "Check code lines against some heuristics"

on:
  push:
  # change to pull_request: 

jobs:
  check_changed_lines:
    name: Check changed lines
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Look around
        run: pwd && ls
      - name: Whatever
        shell: bash
        run: bash ./.github/scripts/scrubber.sh
